---
- name: Deploy Nginx Web Server
  hosts: web_servers
  become: true

  vars:
    web_hosts:
      - "serverc.lab.example.com"
    web_ports:
      - http
      - https
    nginx_packages:
      - '@nginx:1.16'
    cacert_file: "example-ca.crt"

  tasks:
    - name: Install latest Nginx software
      yum:
        name: "{{ nginx_packages }}"
        state: present

    - name: Deploy web content
      import_tasks: deploy_content.yml

    - name: Define the Nginx server block
      template:
        src: "nginx.conf.j2"
        dest: "/etc/nginx/conf.d/{{ item }}.conf"
      loop: "{{ web_hosts }}"

    - name: Open the web services firewall ports
      firewalld:
        service: "{{ item }}"
        permanent: yes
        immediate: yes
        state: enabled
      loop: "{{ web_ports }}"

    - name: Start and enable the Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
