#!/bin/bash
#
# Copyright 2020 Red Hat, Inc.
#
# NAME
#     filestorage-nfs - grading script for RH358 Exporting NFS File Systems
#                       guided exercise
#
# SYNOPSIS
#     filestorage-nfs {start|finish}
#
#        start   - prepare the system for starting the lab
#        finish  - perform post-lab cleanup
#
# DESCRIPTION
#     This script, based on singular argument, either does start
#     or finish for the Exporting NFS File Systems guided exercise.
#
# CHANGELOG
#   * Wed May 20 2020 Herve Quatremain <hquatrem@redhat.com>
#   - original code


PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Initialize and set some variables
run_as_root='true'
target_a='servera'
target_b='serverb'
target_d='serverd'
nfs_share_dir='/nfsshare'
nfs_mount_point='/share'

# This defines which subcommands are supported (start, grade, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(start finish)


function lab_start {

  print_header 'Starting lab.'

  print_line "Preparing ${target_a}, ${target_b}, and ${target_d} for lab exercise work:"
  print_line
  host_reachable ${target_a} ${target_b} ${target_d}

  pad " · Backing up /etc/fstab on ${target_a}"
  if ${ssh} ${target_a} "test -s /var/tmp/lab-${problem_name}-fstab || cp /etc/fstab /var/tmp/lab-${problem_name}-fstab"
  then
    print_SUCCESS
  else
    print_FAIL
  fi

  pad " · Backing up /etc/fstab on ${target_b}"
  if ${ssh} ${target_b} "test -s /var/tmp/lab-${problem_name}-fstab || cp /etc/fstab /var/tmp/lab-${problem_name}-fstab"
  then
    print_SUCCESS
  else
    print_FAIL
  fi

  print_line
}


function lab_finish {

  print_header "Cleaning up the lab on ${target_a}, ${target_b}, and ${target_d}:"
  host_reachable ${target_a} ${target_b} ${target_d}

  pad " · Unmounting the share on ${target_a}"
  ${ssh} ${target_a} "umount -afl -t nfs ; umount -afl -t nfs4 ; sleep 5"
  print_SUCCESS

  pad " · Removing the mount point from ${target_a}"
  ${ssh} ${target_a} "rm -rf ${nfs_mount_point}" &
  print_SUCCESS

  pad " · Restoring /etc/fstab on ${target_a}"
  ${ssh} ${target_a} "test -s /var/tmp/lab-${problem_name}-fstab && cp /var/tmp/lab-${problem_name}-fstab /etc/fstab ; rm -f /var/tmp/lab-${problem_name}-fstab"
  print_SUCCESS

  pad " · Unmounting the share on ${target_b}"
  ${ssh} ${target_b} "umount -afl -t nfs ; umount -afl -t nfs4 ; sleep 5"
  print_SUCCESS

  pad " · Removing the mount point from ${target_b}"
  ${ssh} ${target_b} "rm -rf ${nfs_mount_point}" &
  print_SUCCESS

  pad " · Restoring /etc/fstab on ${target_b}"
  ${ssh} ${target_b} "test -s /var/tmp/lab-${problem_name}-fstab && cp /var/tmp/lab-${problem_name}-fstab /etc/fstab ; rm -f /var/tmp/lab-${problem_name}-fstab"
  print_SUCCESS

  pad " · Stopping the nfs-server service on ${target_d}"
  ${ssh} ${target_d} "systemctl disable --now nfs-server.service"
  print_SUCCESS

  pad " · Cleaning up NFS exports on ${target_d}"
  ${ssh} ${target_d} "rm -f /etc/exports.d/* ; > /etc/exports"
  print_SUCCESS

  pad " · Removing the shared directory from ${target_d}"
  ${ssh} ${target_d} "rm -rf ${nfs_share_dir}"
  print_SUCCESS

  pad " · Closing the firewall port on ${target_d}"
  ${ssh} ${target_d} 'firewall-cmd --remove-service=nfs --remove-service=nfs3 --permanent ; firewall-cmd --remove-port=2049/tcp --remove-port=2049/udp --permanent ; firewall-cmd --reload'
  print_SUCCESS

  print_line
  print_line 'Lab finished.'
  print_line
}

############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
