#!/bin/bash
#
# Copyright 2020 Red Hat, Inc.
#
# NAME
#     lab-database-intro - grading script for RH358 Installing a MariaDB
#                          Database guided exercise.
#
# SYNOPSIS
#     lab-database-intro {start|finish}
#
#        start   - prepare the system for starting the lab
#        finish  - perform post-lab cleanup
#
# DESCRIPTION
#     This script, based on singular argument, either does start or finish
#     for the RH358 Installing a MariaDB Database guided exercise.
#
# CHANGELOG
#   * Wed May 06 2020 Victor Costea <vcostea@redhat.com>
#   - Add function to remove database files not removed by yum
#   * Mon May 04 2020 Victor Costea <vcostea@redhat.com>
#   - original code

#########################################################################
#########################################################################

PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Initialize and set some variables
run_as_root='true'

targeta='servera'

ge_playbook_dir="classroom/ansible"
ge_playbook_tar="${problem_name}.tar"
ge_install_playbook='playbook.yml'
ge_remove_db='remove_mariadb.yml'
ge_install_pkgs='install_packages.yml'

# This defines which subcommands are supported (start, grade, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(start finish)


function lab_start {

  print_line "Starting the ${problem_name} exercise:"
  print_line
  host_reachable ${targeta}

  #
  # Download playbook directory to /tmp
  #
  pad ' · Download exercise playbooks'
  cmd1="curl -o /tmp/${ge_playbook_tar} http://materials.example.com/${ge_playbook_dir}/${ge_playbook_tar}"
  if ${cmd1}
  then
    tar -xf /tmp/${ge_playbook_tar} -C /tmp
    rm -rf /tmp/${ge_playbook_tar}
    print_SUCCESS
  else
    print_FAIL
  fi

  #
  # Run playbook to ensure mariadb is not installed
  # Run playbook to ensure python 3 is installed
  #
  pad ' · Ensure mariadb is not installed'
  cmd1="ansible-playbook ${ge_remove_db}"
  cmd2="ansible-playbook ${ge_install_pkgs}"
  cd /tmp/${problem_name}
  if ${cmd1} && ${cmd2}
  then
    cd
    rm -rf /tmp/${problem_name}
    print_SUCCESS
  else
    print_FAIL
  fi

  print_line
}


function lab_finish {

  print_header "Cleaning up the ${problem_name} exercise on ${targeta}:"
  host_reachable ${targeta}

  #
  # Download playbook directory
  #
  pad ' · Download exercise playbooks'
  cmd1="curl -o /tmp/${ge_playbook_tar} http://materials.example.com/${ge_playbook_dir}/${ge_playbook_tar}"
  if ${cmd1}
  then
    tar -xf /tmp/${ge_playbook_tar} -C /tmp
    rm -rf /tmp/${ge_playbook_tar}
    print_SUCCESS
  else
    print_FAIL
  fi

  #
  # Run playbook to cleanup GE exercise
  #
  pad ' · Run exercise cleanup playbooks'
  cmd1="ansible-playbook ${ge_remove_db}"
  cd /tmp/${problem_name}
  if ${cmd1}
  then
    cd
    rm -rf /tmp/${problem_name}
    print_SUCCESS
  else
    print_FAIL
  fi

  print_line
  print_line 'Lab finished.'
  print_line
}

############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
