#!/bin/bash
#
# Copyright 2020 Red Hat, Inc.
#
# NAME
#     lab-dns-unbound - grading script for RH358 name cacheing DNS
#                       guided exercise.
#
# SYNOPSIS
#     lab-dns-unbound {start|finish}
#
#        start   - prepare the system for starting the lab
#        finish  - perform post-lab cleanup
#
# DESCRIPTION
#     This script, based on singular argument, either does start, or finish
#     for the RH358 Name Cacheing DNS guided exercise.
#
# CHANGELOG
#   * Fri Jun 12 2020 George Hacker <ghacker@redhat.com>
#   - Call rhel_erase_unbound() library function
#   - Require bastion to be reachable for start/finish
#   * Fri Apr 10 2020 Victor Costea <vcostea@redhat.com>
#   - Update package removal code with GH suggestion
#   - Remove dns service from firewall in start/finish
#   * Fri Mar 31 2020 Dallas Spohn <dspohn@redhat.com>
#   - original code

PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Initialize and set some variables
run_as_root='true'
target='servera'

reqd_package1='unbound'
unbound_configs='/etc/unbound/unbound.conf*'

declare -a valid_commands=(start finish)

function lab_start {

  print_header "Starting ${problem_name} exercise."

  host_reachable bastion ${target}

  # For this GE replace dnsmasq with BIND on bastion
  rhel_bastion_bind

  # Remove Unbound from ${target}
  rhel_erase_unbound ${target}

  print_line
}

function lab_finish {

  print_header "Finishing ${problem_name} exercise."

  host_reachable bastion ${target}

  # Unconfigure BIND and restore dnsmasq on bastion
  rhel_bastion_unbind

  # Remove Unbound from ${target}
  rhel_erase_unbound ${target}

  print_line
}

############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
